# Site settings
title: Aditya Rana blog
email: adityassrana2@gmail.com
description: ""
baseurl: "/blog"
url: "https://adityassrana.github.io"
twitter_username: adityassrana
github_username:  adityassrana

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
