# Site settings
title: Aditya Rana blog
email: 
description: ""
baseurl: "/beginagain"
url: "https://adityassrana.github.io"
twitter_username: lukeario
github_username:  adityassrana

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
